source "https://rubygems.org"

ruby "3.0.0"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

gem "bootsnap", require: false

gem 'devise'

gem 'pundit'

gem 'sidekiq'

gem 'redis'

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
end

